### ISSUE TITLE
gnome-abrt doesn't start

### ISSUE THREAD

**Issue by elad661** [abrt/gnome-abrt#114]
gnome-abrt-1.1.0-1.fc22.x86_64

It crashes on startup.
````
Namespace(expert=False, problem=None, verbose=None)
/usr/lib64/python3.4/site-packages/gi/overrides/__init__.py:306: Warning: The property GSettings:schema is deprecated and shouldn't be used anymore. It will be removed in a future version.
  return super_init_func(self, **new_kwargs)

(gnome-abrt:3375): Gtk-CRITICAL **: gtk_header_bar_pack: assertion 'gtk_widget_get_parent (widget) == NULL' failed
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-0/.lock' (no or corrupted 'time' file)
'/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-0' is not a problem directory
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-2/.lock' (no or corrupted 'time' file)
'/home/elad/.cache/abrt/spool/oops-2014-05-23-14:00:26-2406-2' is not a problem directory
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-2/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-2/.lock' (no or corrupted 'time' file)
'/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-2' is not a problem directory
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:20-29587-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:20-29587-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:20-29587-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:20-29587-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:20-29587-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:20-29587-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:20-29587-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:20-29587-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:20-29587-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:20-29587-0/.lock' (no or corrupted 'time' file)
'/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:20-29587-0' is not a problem directory
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-0/.lock' (no or corrupted 'time' file)
Unlocked '/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-0/.lock' (no or corrupted 'time' file)
'/home/elad/.cache/abrt/spool/oops-2014-05-23-12:56:13-29530-0' is not a problem directory
ERROR:root:local variable 'app' referenced before assignment
Traceback (most recent call last):
  File "/usr/bin/gnome-abrt", line 275, in do_activate
    main_window = OopsWindow(self, self.all_sources, controller)
  File "/usr/lib64/python3.4/site-packages/gnome_abrt/views.py", line 469, in __init__
    self._reload_problems(self._source)
  File "/usr/lib64/python3.4/site-packages/gnome_abrt/views.py", line 700, in _reload_problems
    storage_problems.append(problem_to_storage_values(p))
  File "/usr/lib64/python3.4/site-packages/gnome_abrt/views.py", line 127, in problem_to_storage_values
    app = problem.get_application()
  File "/usr/lib64/python3.4/site-packages/gnome_abrt/problems.py", line 275, in get_application
    self['pid'])
  File "/usr/lib64/python3.4/site-packages/gnome_abrt/application.py", line 39, in find_application
    if not app:
UnboundLocalError: local variable 'app' referenced before assignment
```

**Comment by jfilak** [comment]
Thank you for the report! Commit 6b2ca4019c0c43e4e9ea6a5f59871b8286dc9818 fixes this crash (gnome-abrt-1.1.0-2.fc22).
