### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by hadess** [abrt/gnome-abrt#152]
```
ERROR:root:<built-in function get_app_for_cmdline> returned a result with an error set
TypeError: must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/gnome-abrt", line 267, in do_activate
    main_window = OopsWindow(self, self.all_sources, controller)
  File "/usr/lib64/python3.5/site-packages/gnome_abrt/views.py", line 464, in __init__
    self._reload_problems(self._source)
  File "/usr/lib64/python3.5/site-packages/gnome_abrt/views.py", line 688, in _reload_problems
    storage_problems.append(problem_to_storage_values(p))
  File "/usr/lib64/python3.5/site-packages/gnome_abrt/views.py", line 132, in problem_to_storage_values
    app = problem.get_application()
  File "/usr/lib64/python3.5/site-packages/gnome_abrt/problems.py", line 276, in get_application
    self['component'])
  File "/usr/lib64/python3.5/site-packages/gnome_abrt/application.py", line 41, in find_application
    app = wrappers.get_app_for_cmdline(cmdline)
SystemError: <built-in function get_app_for_cmdline> returned a result with an error set
```

gnome-abrt-1.2.1-1.fc24.x86_64

No idea how to debug that. I really wonder why we don't use gobject-introspection for those wrappers...

**Comment by jfilak** [comment]
Thank you for the report. Let me show you how I debug:

1.  I usually start with locating the function where the crash occurred. I use grep to find the definition of the function:
```
$ git clone https://github.com/abrt/gnome-abrt.git
$ cd gnome-abrt
$ grep -r get_app_for_cmdline
src/gnome_abrt/wrappers/problem_app.c:PyObject *p_get_app_for_cmdline(PyObject *module, PyObject *args)
src/gnome_abrt/wrappers/module.c:    { "get_app_for_cmdline", p_get_app_for_cmdline, METH_VARARGS, "Get the application for a specific command-line" },
src/gnome_abrt/wrappers/common.h:PyObject *p_get_app_for_cmdline(PyObject *module, PyObject *args);
src/gnome_abrt/wrappers/__init__.py:                                           get_app_for_cmdline,
src/gnome_abrt/application.py:        app = wrappers.get_app_for_cmdline(cmdline)
```

The files "common.h", "module.c" and "__init__.py" look like boilerplate files and "application.py" is the caller, so the function must be located in "problem_app.c" [1].

2. Then I would try to find the line where the problem occurred. The exception says "returned a result with an error" : "TypeError: must be str, not None". Something that should be of type str is None, so there are two lines where None (can) appear: ```PyArg_ParseTuple(args, "s", &dir_str)``` and ```Py_RETURN_NONE;```

Python has no static types, therefore the return value should not be an issue.  Only the parsing of function arguments could raise the exception.

3. Now, I would try to reproduce the crash [2]:
```
$ pwd
<irrelevant>/gnome-abrt
$ PYTHONPATH=src python3
>>> import gnome_abrt.wrappers
>>> gnome_abrt.wrappers.get_app_for_cmdline(None)
TypeError: must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <built-in function get_app_for_cmdline> returned a result with an error set
>>>
```

Confirmed, passing None the function causes the exception.

4. Let's fix the bug I missed when I was reviewing your commit cdfc81b3380bba744e68e4dab4460853e1c9de23 

```
$ git diff
diff --git a/src/gnome_abrt/application.py b/src/gnome_abrt/application.py
index eb18411..b5ea506 100644
--- a/src/gnome_abrt/application.py
+++ b/src/gnome_abrt/application.py
@@ -37,7 +37,7 @@ def find_application(cmdline, envp, pid, component):
     app = None
     if envp:
         app = wrappers.get_app_for_env(envp.split('\n'), int(pid))
-    if not app:
+    if not app and cmdline:
         app = wrappers.get_app_for_cmdline(cmdline)
     if not app:
         return Application(cmdline.split(" ")[0] if cmdline else None,
```

Thank you!

1: https://github.com/abrt/gnome-abrt/blob/master/src/gnome_abrt/wrappers/problem_app.c#L23
2: https://github.com/abrt/gnome-abrt#running
