### ISSUE TITLE
BeautifulSoup not found on Fedora 32

### ISSUE THREAD

**Issue by toxotescodes** [abrt/gnome-abrt#278]
really a simple problem but should work outside of the box instead of asking deps

do i report here or its a distro problem?

who packs those dependancies? who is responsible for these deps be included?

$ gnome-abrt 
Traceback (most recent call last):
  File "/usr/bin/gnome-abrt", line 45, in <module>
    from gnome_abrt.views import OopsWindow
  File "/usr/lib64/python3.8/site-packages/gnome_abrt/views.py", line 41, in <module>
    from gnome_abrt import problems, config, wrappers, errors
  File "/usr/lib64/python3.8/site-packages/gnome_abrt/problems.py", line 23, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

**Comment by toxotescodes** [comment]
installing BeautifulSoup 4 with:
sudo dnf install -y python3-beautifulsoup4

**Comment by ernestask** [comment]
https://github.com/abrt/gnome-abrt/commit/17acc537dae787754df710ab81e88544c81f17bf
