### ISSUE TITLE
Fails to start on Fedora 34 Silverblue

### ISSUE THREAD

**Issue by vchernin** [abrt/gnome-abrt#306]
Trying to run on Fedora 34 Silverblue I get this error:
To install it I used `rpm-ostree install gnome-abrt` and rebooted.

```bash
$ gnome-abrt
WARNING:root:Can't connect to D-Bus system bus 'org.freedesktop.problems' path '/org/freedesktop/problems': org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
ERROR:root:No available problem source.
Traceback (most recent call last):
  File "/usr/bin/gnome-abrt", line 176, in do_activate
    raise UnavailableSource(None, None,
gnome_abrt.errors.UnavailableSource: No available problem source.
```
It fails to launch using the normal app icon as well.

**Comment by mgrabovsky** [comment]
Could you please share the output of running `abrt status` and `abrt ls` on the terminal?

**Comment by vchernin** [comment]
```bash
$ abrt status
bash: abrt: command not found
$ gnome-abrt status
WARNING:root:Can't connect to D-Bus system bus 'org.freedesktop.problems' path '/org/freedesktop/problems': org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
ERROR:root:No available problem source.
Traceback (most recent call last):
  File "/usr/bin/gnome-abrt", line 176, in do_activate
    raise UnavailableSource(None, None,
gnome_abrt.errors.UnavailableSource: No available problem source.
```

```bash
$ gnome-abrt ls
WARNING:root:Can't connect to D-Bus system bus 'org.freedesktop.problems' path '/org/freedesktop/problems': org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
ERROR:root:No available problem source.
Traceback (most recent call last):
  File "/usr/bin/gnome-abrt", line 176, in do_activate
    raise UnavailableSource(None, None,
gnome_abrt.errors.UnavailableSource: No available problem source.
```

**Comment by vchernin** [comment]
Fixed by installing the `abrt` package. Apparently `gnome-abrt` depends on `abrt` in Fedora 34 Silverblue but that isn't marked correctly. I'll see if can make a Fedora bug for this.
